### ISSUE TITLE
video is not showing 

### ISSUE THREAD

**Issue by betharaghu** [Sachin880699/video-calling-app#1]
please can you help me with this there were no library issues nothing at all but video is not working

**Comment by betharaghu** [comment]
![django_video](https://user-images.githubusercontent.com/51076437/91644897-13e7b880-ea5e-11ea-844b-d19d02a48a2d.JPG)

**Comment by betharaghu** [comment]
helpme

**Comment by iMiebaka** [comment]
You need to be connected to the internet, since your using cdn version of peer.js

**Comment by betharaghu** [comment]
ok done thanks
